FUNCIONARIOS/Models/ErrorViewModel.cs
using System;

namespace FUNCIONARIOS.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FUNCIONARIOS/Models/PaginatedList.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FUNCIONARIOS.Models
{
    public class PaginatedList<T> : List<T>
    {
        public int PageIndex { get; private set; }
        public int TotalPages { get; private set; }

        public PaginatedList(List<T> items, int count, int pageIndex, int pageSize)
        {
            PageIndex = pageIndex;
            TotalPages = (int)Math.Ceiling(count / (double)pageSize);

            this.AddRange(items);
        }

        public bool HasPreviousPage
        {
            get
            {
                return (PageIndex > 1);
            }
        }

        public bool HasNextPage
        {
            get
            {
                return (PageIndex < TotalPages);
            }
        }

        public static PaginatedList<T> CreateAsync(IQueryable<T> source, int pageIndex, int pageSize)
        {
            var count = source.Count();
            var items = source.Skip((pageIndex - 1) * pageSize).Take(pageSize).ToList();
            return new PaginatedList<T>(items, count, pageIndex, pageSize);
        }
    }
}

FUNCIONARIOS/Controllers/FuncionarioController.cs
using FUNCIONARIOS.Data;
using FUNCIONARIOS.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Teste.Colaboradores.BusinessLogic.Services;

namespace FUNCIONARIOS.Controllers
{
    public class FuncionarioController : Controller
    {
        private readonly IFuncionarioServices _FuncionarioService;

        public FuncionarioController(IFuncionarioServices funcionarioService)
        {
            _FuncionarioService = funcionarioService;
        }

        public async Task<IActionResult> Index(string ordem, string filtroAtual, string filtro, int? pagina)
        {
            ViewData["NomeParm"] = String.IsNullOrEmpty(ordem) ? "nome_desc" : "";
            ViewData["CPF"] = ordem == "CPF" ? "cpf_desc" : "Cpf";

            var funcionarios = _FuncionarioService.Listar();

            if (filtro != null)
            {
                 pagina = 1;
            }
            else
            {
                 filtro = filtroAtual;
            }

            if (!String.IsNullOrEmpty(filtro))
            {
                 funcionarios = _FuncionarioService.Listar(s => s.Nome.Contains(filtro)||s.CPF.Contains(filtro));
            }

            switch (ordem)
            {
                case "nome_desc":
                    funcionarios = funcionarios.OrderByDescending(w => w.Nome).ToList();
                    break;
                case "Cpf":
                    funcionarios = funcionarios.OrderByDescending(w => w.CPF).ToList();
                    break;

            }
            int pageSize = 3;
            return View(PaginatedList<Funcionario>.CreateAsync(funcionarios.AsQueryable(), pagina ?? 1, pageSize));
        }

        public ActionResult Create()
        {
            ViewBag.Sexo = Funcionario.GetSexos().Select(c => new SelectListItem() { Text = c.Sexo, Value = c.Sexo }).ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Funcionario funcionario)
        {
            ViewBag.Sexo = Funcionario.GetSexos().Select(c => new SelectListItem() { Text = c.Sexo, Value = c.Sexo }).ToList();
            try
            {
                if (ModelState.IsValid)
                {
                    _FuncionarioService.inserir(funcionario);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(funcionario);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var funcionario = _FuncionarioService.GetById(s => s.IdFuncionario == id);
            return View(funcionario);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id)
        {
            var atualizarFuncionario = _FuncionarioService.GetById(s => s.IdFuncionario == id);
            if (await TryUpdateModelAsync<Funcionario>(
                atualizarFuncionario,
                "",
                s => s.Nome, s => s.CPF, s => s.Sexo, s => s.Salario, s => s.Data_admissao, s => s.Email, s => s.Pis))
            {
                try
                {
                    _FuncionarioService.alterar(atualizarFuncionario);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }
            return View(atualizarFuncionario);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var funcionario = _FuncionarioService.GetById(s => s.IdFuncionario == id);
            return View(funcionario);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var funcionario = _FuncionarioService.GetById(m => m.IdFuncionario == id);
            if (funcionario == null)
            {
                return RedirectToAction("Index");
            }
            try
            {
                _FuncionarioService.excluir(funcionario.IdFuncionario);

                return RedirectToAction("Index");
            }
            catch (DbUpdateException)
            {

                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }
        }

        public async Task<IActionResult> DespesasSalColaborador()
        {
            var funcionario = new Funcionario();
            var funcionarios = _FuncionarioService.Listar();

            funcionario.TotalSalarios = funcionarios.OrderByDescending(o => o.Salario).ToList();

            ViewBag.TotalSalarios = string.Format("{0:c}", funcionario.TotalSalarios.Sum(w => w.Salario));

            return View(funcionario.TotalSalarios);
        }
    }
}

FUNCIONARIOS/Controllers/HomeController.cs
using FUNCIONARIOS.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FUNCIONARIOS.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FUNCIONARIOS/Views/Funcionario/Create.cshtml
@model FUNCIONARIOS.Models.Funcionario

@{
    ViewData["Title"] = "Create";
}

<h4>Funcionario</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Create">
            <div class="col-sm-6">
                <div class="form-group">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" placeholder="Digite aqui o nome" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
            </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label asp-for="Sexo" class="control-label"></label>
                         <select  asp-for="Sexo" class="form-control" asp-items="ViewBag.Sexo"></select>
                        <span asp-validation-for="Sexo" class="text-danger"></span>
                    </div>


                </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label asp-for="Pis" class="control-label"></label>
                    <input asp-for="Pis" class="form-control" />
                    <span asp-validation-for="Pis" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label asp-for="CPF">CPF</label>
                    <input asp-for="CPF" onblur="validarCPF(this)" class="form-control cpf" placeholder="123.456.789-10" />
                    <span asp-validation-for="CPF" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label asp-for="Salario" class="control-label"></label>
                    <input asp-for="Salario" class="form-control" placeholder="R$ 0.00"  />
                    <span asp-validation-for="Salario" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label asp-for="Data_admissao" class="control-label"></label>
                    <input asp-for="Data_admissao" class="form-control" />
                    <span asp-validation-for="Data_admissao" class="text-danger"></span>
                    <br />
                    <input type="submit" value="Salvar" class="btn btn-primary" />
                    <a class="btn btn-danger" asp-action="Index">Voltar</a>
                </div>
            </div>
            <br />
            <div class="col-sm-6">
                <div class="form-group">

                </div>
            </div>         
        </form>
    </div>
</div>


<script>function _cpf(cpf) {
        cpf = cpf.replace(/[^\d]+/g, '');
        if (cpf == '') return false;
        if (cpf.length != 11 ||
            cpf == "00000000000" ||
            cpf == "11111111111" ||
            cpf == "22222222222" ||
            cpf == "33333333333" ||
            cpf == "44444444444" ||
            cpf == "55555555555" ||
            cpf == "66666666666" ||
            cpf == "77777777777" ||
            cpf == "88888888888" ||
            cpf == "99999999999")
            return false;
        add = 0;
        for (i = 0; i < 9; i++)
            add += parseInt(cpf.charAt(i)) * (10 - i);
        rev = 11 - (add % 11);
        if (rev == 10 || rev == 11)
            rev = 0;
        if (rev != parseInt(cpf.charAt(9)))
            return false;
        add = 0;
        for (i = 0; i < 10; i++)
            add += parseInt(cpf.charAt(i)) * (11 - i);
        rev = 11 - (add % 11);
        if (rev == 10 || rev == 11)
            rev = 0;
        if (rev != parseInt(cpf.charAt(10)))
            return false;
        return true;

    function validarCPF(el) {
        if (!_cpf(el.value)) {

            alert("CPF inválido! " + el.value);

  
            el.value = "";
        }

    }</script>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FUNCIONARIOS/Views/Funcionario/Delete.cshtml
@model FUNCIONARIOS.Models.Funcionario

@{
    ViewData["Title"] = "Delete";
}

<h3>Você tem certeza que deseja deletar?</h3>
<div>
    <h4>Funcionario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdFuncionario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdFuncionario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sexo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data_admissao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data_admissao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Deletar" class="btn btn-danger" /> |
        <a class="btn btn-danger" asp-action="Index">Voltar</a>
    </form>
</div>

FUNCIONARIOS/Views/Funcionario/DespesasSalColaborador.cshtml
@model IEnumerable<FUNCIONARIOS.Models.Funcionario>

@{
    ViewData["Title"] = "DESPESAS";
}

<h2>Despesas com Salários</h2>


<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sexo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pis)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CPF)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data_admissao)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sexo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pis)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CPF)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data_admissao)
            </td>
        </tr>
        }
    </tbody>

</table>
<div class="p-3 d-flex justify-content-between">
    <div class="d-flex justify-content-between">
        <h5>
            <strong>Total Gasto com Salários:&nbsp;</strong>
        </h5>
        <h5 id="saldoDevedor">@ViewBag.TotalSalarios</h5>
    </div>
</div>

FUNCIONARIOS/Views/Funcionario/Details.cshtml
@model FUNCIONARIOS.Models.Funcionario

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Funcionario</h4>
    <hr />
    <dl class="row">
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdFuncionario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sexo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pis)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CPF)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CPF)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data_admissao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data_admissao)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

FUNCIONARIOS/Views/Funcionario/Edit.cshtml
@model FUNCIONARIOS.Models.Funcionario

@{
    ViewData["Title"] = "Edit";
}


<h4>Funcionario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label asp-for="Sexo" class="control-label"></label>
                    <input asp-for="Sexo" class="form-control" />
                    <span asp-validation-for="Sexo" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label asp-for="Pis" class="control-label"></label>
                    <input asp-for="Pis" class="form-control" />
                    <span asp-validation-for="Pis" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label asp-for="CPF" class="control-label"></label>
                    <input asp-for="CPF" class="form-control" />
                    <span asp-validation-for="CPF" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label asp-for="Salario" class="control-label"></label>
                    <input asp-for="Salario" class="form-control" />
                    <span asp-validation-for="Salario" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label asp-for="Data_admissao" class="control-label"></label>
                    <input asp-for="Data_admissao" class="form-control" />
                    <span asp-validation-for="Data_admissao" class="text-danger"></span>
                    <br />
                    <div class="form-group">
                        <input type="submit" value="Salvar" class="btn btn-primary" />
                        <a class="btn btn-danger" asp-action="Index">Voltar</a>
                    </div>
                </div>
            </div>

        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FUNCIONARIOS/Views/Funcionario/Index.cshtml
@model PaginatedList<FUNCIONARIOS.Models.Funcionario>

@{
    ViewData["Title"] = "Index";
}

<br />

<br />
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">
                <a asp-action="Index" asp-route-ordem="@ViewData["NomeParm"]" asp-route-filtroAtual="@ViewData["filtroAtual"]">Nome</a>
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Sexo)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model[0].Pis)
            </th>
            <th scope="col">
                <a asp-action="Index" asp-route-ordem="@ViewData["CPF"]" asp-route-filtroAtual="@ViewData["filtroAtual"]">CPF</a>
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model[0].Salario)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model[0].Email)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model[0].Data_admissao)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sexo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Pis)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CPF)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Salario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data_admissao)
                </td>
                <td>
                    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.IdFuncionario">Editar</a> |
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.IdFuncionario">Deletar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@{ var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : ""; }

<a asp-action="Index"
   asp-route-ordem="@ViewData["ordemAtual"]"
   asp-route-pagina="@(Model.PageIndex - 1)"
   asp-route-filtroAtual="@ViewData["filtroAtual"]"
   class="btn btn-default @prevDisabled">
    <strong><</strong> <!--ANTERIOR-->
</a>
<a asp-action="Index"
   asp-route-ordem="@ViewData["ordemAtual"]"
   asp-route-pagina="@(Model.PageIndex + 1)"
   asp-route-filtroAtual="@ViewData["filtroAtual"]"
   class="btn btn-default @nextDisabled">
    <strong>></strong> <!--PROXIMO-->
</a>
@*<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            <br />
            Pesquisar: <input class="form-control" type="text" name="filtro" value="@ViewData["filtroAtual"]" />
            <br />
            <input type="submit" value="Procurar" class="btn btn-primary" /> |
            <a class="btn btn-secondary" asp-action="Index">Voltar</a> |
            <a class="btn btn-success" asp-action="Create">Novo</a>
        </p>
    </div>
</form>*@

FUNCIONARIOS/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FUNCIONARIOS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="icon" href="favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="~/lib/assets/css/normalize.css">
    <link rel="stylesheet" href="~/lib/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/lib/assets/css/fontello.css">
    <link href="~/lib/assets/fonts/icon-7-stroke/css/pe-icon-7-stroke.css" rel="stylesheet">
    <link href="~/lib/assets/fonts/icon-7-stroke/css/helper.css" rel="stylesheet">
    <link href="~/lib/assets/css/animate.css" rel="stylesheet" media="screen">
    <link rel="stylesheet" href="~/lib/assets/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/assets/css/icheck.min_all.css">
    <link rel="stylesheet" href="~/lib/assets/css/price-range.css">
    <link rel="stylesheet" href="~/lib/assets/css/owl.carousel.css">
    <link rel="stylesheet" href="~/lib/assets/css/owl.theme.css">
    <link rel="stylesheet" href="~/lib/assets/css/owl.transitions.css">
    <link rel="stylesheet" href="~/lib/assets/css/style.css">
    <link rel="stylesheet" href="~/lib/assets/css/responsive.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                    <a class="navbar-brand" href="#"></a>

                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Funcionario" asp-action="Index">Funcionários</a>

                        </li>
                    </ul>
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Funcionario" asp-action="DespesasSalColaborador">Despesas</a>
                        </li>
                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-action="Index" method="get">
                        <div class="form-actions no-color">
                            <p>

                                <div>
                                    Pesquisar: <input class="form-control" type="text" name="filtro" value="@ViewData["filtroAtual"]" />
                                    <input type="submit" value="Procurar" class="btn btn-primary" /> |
                                    <a class="btn btn-secondary" asp-action="Index">Voltar</a> |
                                    <a class="btn btn-success" asp-action="Create">Novo</a>
                                </div>
                            </p>
                        </div>
                    </form>

                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FUNCIONARIOS - <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="assets/js/modernizr-2.6.2.min.js"></script>

    <script src="~/lib/assets/js/jquery-1.10.2.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/assets/js/bootstrap-select.min.js"></script>
    <script src="~/lib/assets/js/bootstrap-hover-dropdown.js"></script>

    <script src="~/lib/assets/js/easypiechart.min.js"></script>
    <script src="~/lib/assets/js/jquery.easypiechart.min.js"></script>

    <script src="~/lib/assets/js/owl.carousel.min.js"></script>
    <script src="~/lib/assets/js/wow.js"></script>

    <script src="~/lib/assets/js/icheck.min.js"></script>
    <script src="~/lib/assets/js/price-range.js"></script>

    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=false"></script>
    <script src="~/lib/assets/js/gmaps.js"></script>
    <script src="~/lib/assets/js/gmaps.init.js"></script>

    <script src="~/lib/assets/js/main.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>